### ISSUE TITLE
Ran into some requirements issues with PyYaml==6.0

### ISSUE THREAD

**Issue by dan-osms** [aws-samples/access-analyzer-automated-policy-analysis-blog#1]
Upon the installation of required components I get 
```
❯ pip3 install -r requirements.txt
Collecting aws-cdk-lib==2.99.1 (from -r requirements.txt (line 1))
  Using cached aws_cdk_lib-2.99.1-py3-none-any.whl.metadata (55 kB)
Collecting constructs==10.1.162 (from -r requirements.txt (line 2))
  Using cached constructs-10.1.162-py3-none-any.whl.metadata (2.6 kB)
Collecting PyYAML==6.0 (from -r requirements.txt (line 3))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/some_user/Projects/access-analyzer-automated-policy-analysis-blog/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/some_user/Projects/access-analyzer-automated-policy-analysis-blog/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/some_user/Projects/access-analyzer-automated-policy-analysis-blog/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1 aws-cdk-lib==2.99.1
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/tz/3k6jxs1s63d_wj_2ymtj34tr0000gr/T/pip-build-env-f3x9qxio/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```
While installing 6.0 of PyYAML. Checking the web, I noticed others were having challenges with that version pinned for other projects. So I updated PyYAML to 6.0.1 and retried to install and it worked. 

Running on Apple M3 Silicon, 🤷🏻 unclear what with 6.0 doesn't work, but 6.0.1 definitely installed without a problem. I have a hunch it may be related to as `6.0 was broken by Cython 3.0 release, they patched it in 6.0.1`

**Comment by shdobxr** [comment]
Other repo where information was sourced for those that were curious. 

https://github.com/python-poetry/poetry/issues/8287
